const employee = [
  {
    id: 1,
    username: "rahul_sharma",
    email: "m@m.com",
    password: "123",
    taskCount: {
      active: 1,
      newTask: 1,
      completed: 2,
      failed: 1,
      pending: 1,
    },
    tasks: [
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        priority: "high",
        title: "Prepare sales report",
        description: "Monthly sales report for July.",
        date: "2025-07-05",
        category: "Reporting",
      },
      {
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        priority: "urgent",
        title: "Finalize presentation",
        description: "Prepare slides for board meeting.",
        date: "2025-07-07",
        category: "Presentation",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        priority: "medium",
        title: "Follow up with client",
        description: "Call client for feedback.",
        date: "2025-07-03",
        category: "Client",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        priority: "low",
        title: "Organize files",
        description: "Arrange and clean project folders.",
        date: "2025-07-04",
        category: "Admin",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        priority: "high",
        title: "Client payment follow-up",
        description: "Check pending invoices.",
        date: "2025-07-06",
        category: "Finance",
      },
    ],
  },
  {
    id: 2,
    username: "priya_verma",
    email: "priya.verma@example.com",
    password: "123",
    taskCount: {
      active: 1,
      newTask: 1,
      completed: 2,
      failed: 1,
      pending: 1,
    },
    tasks: [
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        priority: "medium",
        title: "Review designs",
        description: "Check UI design updates.",
        date: "2025-07-07",
        category: "Design",
      },
      {
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        priority: "high",
        title: "Plan design sprint",
        description: "Outline tasks for upcoming sprint.",
        date: "2025-07-08",
        category: "Planning",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        priority: "low",
        title: "Send team update",
        description: "Weekly update to design team.",
        date: "2025-07-05",
        category: "Communication",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        priority: "medium",
        title: "Test prototype",
        description: "Run user tests on new design prototype.",
        date: "2025-07-03",
        category: "Testing",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        priority: "urgent",
        title: "Budget draft",
        description: "Draft Q3 budget proposal.",
        date: "2025-07-04",
        category: "Finance",
      },
    ],
  },
  {
    id: 3,
    username: "aisha_khan",
    email: "aisha.khan@example.com",
    password: "123",
    taskCount: {
      active: 1,
      newTask: 1,
      completed: 2,
      failed: 1,
      pending: 1,
    },
    tasks: [
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        priority: "medium",
        title: "Update social media",
        description: "Post product update on LinkedIn.",
        date: "2025-07-05",
        category: "Marketing",
      },
      {
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        priority: "high",
        title: "Plan marketing campaign",
        description: "Outline July social media campaign.",
        date: "2025-07-06",
        category: "Planning",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        priority: "low",
        title: "Handle support tickets",
        description: "Clear pending tickets in system.",
        date: "2025-07-03",
        category: "Support",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        priority: "medium",
        title: "Create content calendar",
        description: "Plan content for August.",
        date: "2025-07-04",
        category: "Content",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        priority: "urgent",
        title: "Follow up with leads",
        description: "Call warm leads from last week.",
        date: "2025-07-05",
        category: "Sales",
      },
    ],
  },
  {
    id: 4,
    username: "arjun_patel",
    email: "arjun.patel@example.com",
    password: "123",
    taskCount: {
      active: 1,
      newTask: 1,
      completed: 2,
      failed: 1,
      pending: 1,
    },
    tasks: [
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        priority: "medium",
        title: "Update website banner",
        description: "Change homepage banner image.",
        date: "2025-07-05",
        category: "Web",
      },
      {
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        priority: "high",
        title: "Setup staging server",
        description: "Prepare server for testing deployments.",
        date: "2025-07-06",
        category: "DevOps",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        priority: "low",
        title: "Inventory check",
        description: "Check office supply stock.",
        date: "2025-07-03",
        category: "Logistics",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        priority: "medium",
        title: "Code review",
        description: "Review PRs from junior developers.",
        date: "2025-07-04",
        category: "Development",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        priority: "urgent",
        title: "Fix critical bug",
        description: "Resolve server downtime issue.",
        date: "2025-07-05",
        category: "Bugfix",
      },
    ],
  },
  {
    id: 5,
    username: "isha_singh",
    email: "isha.singh@example.com",
    password: "123",
    taskCount: {
      active: 1,
      newTask: 1,
      completed: 4,
      failed: 1,
      pending: 1,
    },
    tasks: [
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        priority: "high",
        title: "Onboard intern",
        description: "Prepare laptop and tools for intern.",
        date: "2025-07-05",
        category: "HR",
      },
      {
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        priority: "urgent",
        title: "Schedule interviews",
        description: "Set up interviews for new candidates.",
        date: "2025-07-06",
        category: "Recruitment",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        priority: "medium",
        title: "Send project update",
        description: "Weekly update to stakeholders.",
        date: "2025-07-03",
        category: "Project",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        priority: "low",
        title: "Update HR policies",
        description: "Review and update internal policies.",
        date: "2025-07-04",
        category: "HR",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        priority: "high",
        title: "Resolve payroll issue",
        description: "Check July payroll discrepancies.",
        date: "2025-07-05",
        category: "Finance",
      },
    ],
  },
];

const admin = [
  {
    id: 1,
    username: "admin_Morkal",
    email: "admin@example.com",
    password: "123",
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employee", JSON.stringify(employee));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
  const employee = JSON.parse(localStorage.getItem("employee"));
  const admin = JSON.parse(localStorage.getItem("admin"));

  return { employee, admin };
};
